app/urls.py
from django.urls import path

from . import views

app_name = 'app' 
urlpatterns=[
    path('index/', views.index, name='index'),
    path('index/perfil/', views.iniciar_sesion, name='iniciar_sesion'),
    # path('index/estudiante/', views.estudiante, name='estudiante'),
    # path('index/estudiante/', views.estudiante, name='estudiante'), 
    # verGrupoEstudiante
    # path('index/estudiante/verGrupoEstudiante/<int:id>/', views.verGrupoEstudiante, name='verGrupoEstudiante'),
    path('index/estudiante/verGrupoEstudiante/<int:idgrupo>/<int:idestudiante>/', views.verGrupoEstudiante, name='verGrupoEstudiante'),
    path('logout/', views.cerrarsesion, name='cerrarsesion'),

    path('index/profesor/crearAcividadProfesor/<int:id>/', views.crearAcividadProfesor, name='crearAcividadProfesor'),
    # path('index/profesor/', views.crearActividadProfesorForm, name='crearActividadProfesorForm'),
    path('index/profesor/editaractividadForm/<int:id>/', views.editaractividadForm, name='editaractividadForm'),
    path('index/profesor/editaractividad/<int:id>/', views.editaractividad, name='editaractividad'),
    path('index/profesor/crearActividadProfesorForm/', views.crearActividadProfesorForm, name='crearActividadProfesorForm'),
    path('index/profesor/verGrupoProfesor/<int:id>/', views.verGrupoProfesor, name='verGrupoProfesor'),
    path('index/profesor/verActividadProfesor/<int:idactividad>/<int:idgrupo>/', views.verActividadProfesor, name='verActividadProfesor'),
    path('index/profesor/verEstudianteComoProfesor/<int:idestudiante>/<int:idgrupo>/', views.verEstudianteComoProfesor, name='verEstudianteComoProfesor'),
    path('index/profesor/cambiarnota/<int:idgrupoestudiante>/<int:idactividad>/', views.cambiarnota, name='cambiarnota'),
    path('index/admin/', views.admin, name='admin'), 
    path('index/admin/verListaEstudiantes', views.verListaEstudiantes, name='verListaEstudiantes'),
    path('index/admin/eliminargrupo/<int:id>/', views.eliminargrupo, name='eliminargrupo'),
    path('index/admin/editarEstudiante/<int:id>/', views.editarEstudiante, name='editarEstudiante'),
    path('index/admin/editarestudianteForm/<int:id>/', views.editarestudianteForm, name='editarestudianteForm'),
    path('index/admin/verGruposComoAdmin', views.verGruposComoAdmin, name='verGruposComoAdmin'),
    path('index/admin/verGrupoindividualAdmin/<int:id>/', views.verGrupoindividualAdmin, name='verGrupoindividualAdmin'), #REVISAR
    path('index/admin/editarGrupoAdmin/<int:id>/', views.editarGrupoAdmin, name='editarGrupoAdmin'),
    path('index/admin/editarGrupoAdminForm/<int:id>/', views.editarGrupoAdminForm, name='editarGrupoAdminForm'),
    path('index/admin/agregarEstudianteAGrupo/<int:id>/', views.agregarEstudianteAGrupo, name='agregarEstudianteAGrupo'),
    path('index/admin/agregarestudianteagrupoForm/<int:idestudiante>/<int:idgrupo>', views.agregarestudianteagrupoForm, name='agregarestudianteagrupoForm'),
    path('index/admin/verProfesores', views.verProfesores, name='verProfesores'),
    path('index/admin/crearGrupoAdmin', views.crearGrupoAdmin, name='crearGrupoAdmin'),
    path('index/admin/crearProfesor', views.crearProfesor, name='crearProfesor'),
    path('index/admin/crearProfesorForm', views.crearProfesorForm, name='crearProfesorForm'),
    path('index/admin/crearEstudiante', views.crearEstudiante, name='crearEstudiante'),
    path('index/admin/crearEstudianteForm', views.crearEstudianteForm, name='crearEstudianteForm'),
    path('index/admin/crearGrupoForm', views.crearGrupoForm, name='crearGrupoForm'),
    path('index/error',views.error, name = 'error'),
    path('index/completado',views.completado, name = 'completado'),
    path('index/admin/listaDeCursosProfe/<int:id>',views.listaDeCursosProfe, name = 'listaDeCursosProfe'),
    

]

pagina_login/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('app.urls')),
    path('admin/', admin.site.urls),
]

app/templates/app/admin.html
{% extends "app/base.html" %} {% load static %} {%block css%}
<link rel="stylesheet" href="{% static 'app/css/estilo.css' %}"> {%endblock%} {%block titulo%} Admin {%endblock%} {%block body%}
<h1>Bienvenido Administrador</h1>

<p class="InformacionUsuario">
    <br>
    <h2 style="color: wheat;">

        <p>{{ request.user.first_name }} </p>
    </h2>
</p>
<a href="{% url 'app:cerrarsesion' %}">
    <input class="cerrarsesion" type="submit" value="Cerrar Sesión">
</a>
<img src="{% static 'app/img/profilephoto.png' %}" alt="profilephoto" width="180">
<br>
<br>
<a href="{% url 'app:verListaEstudiantes' %}" target="_blank">
    <input class="Boton" type="submit" value="Ver estudiantes">
</a>
<br>
<br>
<a href="{% url 'app:verGruposComoAdmin' %}" target="_blank">
    <input class="Boton" type="submit" value="Ver grupos">
</a>
<br>
<br>
<a href="{% url 'app:verProfesores' %}" target="_blank">
    <input class="Boton" type="submit" value="Ver profesores">
</a>
<br>
<br>
<a href="{% url 'app:crearGrupoAdmin' %}" target="_blank">
    <input class="Boton" type="submit" value="Crear grupo">
</a>
<br>
<br>
<a href="{% url 'app:crearProfesor' %}" target="_blank">
    <input class="Boton" type="submit" value="Crear profesor">
</a>
<br>
<br>
<a href="{% url 'app:crearEstudiante' %}" target="_blank">
    <input class="Boton" type="submit" value="Crear alumno">
</a>
<div class="logoxd">
    <img src="{% static 'app/img/logo-social.png' %}" alt="logo-social"></div>

{%endblock%}

app/templates/app/autenticacion.html
{% load static %}
<html>
<html lang="es">

<head>
    <meta charset="UTF-8">
    <title>Proyecto Cloud</title>
    <link rel="stylesheet" href="css/estilo.css">
</head>

<body>
    <h1>BIENVENIDO A GRADER</h1>
    <form>
        <div class="autenticacion">

            <h2>USUARIO:</h2>
            <input type="" id="USUARIO">
            <br>
            <h2>CLAVE:</h2>
            <input type="password" id="password">
            <br>
            <br>
        </div>
        <input class="Boton" type="submit" value="Enviar">
    </form>
    <br>
    <br>
    <br>
    <img src="img/AWS.jpg" alt="AWS" width="150">
    <img class="usta" src="img/LOGO_USTA_AZUL.png" alt="Logo usta">
    <br>
    <a href="profesor" target="_blank">Ver como profesor</a>
    <br>
    <a href="admin.html" target="_blank">Ver como admin</a>
    <br>
    <a href="estudiante.html" target="_blank">Ver como estudiante</a>
    <br>
</body>

</html>

app/templates/app/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <script src="https://use.fontawesome.com/8db3925a16.js"></script>
    {%block css%} {%endblock%}


    <title>
        {%block titulo%} {%endblock%}
    </title>
</head>

<body>
    <img src="{% static 'app/img/logo.png' %}" class="logoSistema"> {%block body%} {%endblock%}
</body>

</html>

app/templates/app/completado.html
{% extends "app/base.html" %} {% load static %} {%block css%}
<link rel="stylesheet" href="{% static 'app/css/estilo.css' %}"> {%endblock%} {%block titulo%} Admin {%endblock%} {%block body%}

<h1>Operacion completada satisfactoriamente</h1>

<button onclick="goBack()">RETROCEDER</button>

<script>
    function goBack() {
        window.history.back();
    }
</script>

{%endblock%}

app/templates/app/crearGrupoAdmin.html
{% extends "app/base.html" %} {% load static %} {%block titulo%} Crear Grupo {%endblock%} {%block css%}
<link rel="stylesheet" href="{% static 'app/css/estilocrearestudiante.css' %}"> {%endblock%} {%block body%}

<h1> CREAR GRUPO</h1>
<hr>
<br>
<img src="{% static 'app/img/profilephoto.png' %}" alt="profilephoto" width="180">

<img src="{% static 'app/img/LOGO_USTA_AZUL.png' %}" alt="Logo" class="logoustagrupo" width="200">

<div class="admincreargrupo">

    <a href="{% url 'app:cerrarsesion' %}">
        <input class="cerrargrupo" type="submit" value="Cerrar Sesión">
    </a>

    <form action="{% url 'app:crearGrupoForm' %}" method="POST">
        {% csrf_token %}
        <label for="asignaturain" id="lblasignatura">* Codigo del grupo </label>
        <input type="text" name="codgrupo" placeholder=" Ingrese codigo del grupo" class="inasignatura">
        <br>
        <br>
        <label for="semestrein" id="lblsemestre">* Asignatura </label>
        <input type="text" name="asignatura" placeholder="Ingrese la asignatura" class="insemestre">
        <br>
        <br>
        <label>Profesor </label>
        <select name="profesor" id="profesor">
            {% for ver in profesores%}
            <option value="{{ver.usuario.id}}">{{ver.usuario.last_name}}</option>
            {% endfor %}
        </select>
        <br>
        <br>
        <label for="cantidadin" id="lblcantidad">* Semestre </label>
        <input type="number" name="semestre" class="insemestre" placeholder="Ingrese semestre" min="0" max="10">
        <br>
        <br>
        <button>Enviar</button>
    </form>

</div>

{%endblock%}

app/templates/app/editarEstudiante.html
{% extends "app/base.html" %} {% load static %} {%block css%}
<link rel="stylesheet" href="{% static 'app/css/estilo.css' %}">
<link rel="stylesheet" href="{% static 'app/css/estilocrearestudiante.css' %}"> {%endblock%} {%block titulo%} Editar Estudiante como admin {%endblock%} {%block body%}
<h1> EDITAR ESTUDIANTE</h1>
<hr>
<br>
<img src="{% static 'app/img/profilephoto.png' %}" alt="profilephoto" width="180">
<img src="{% static 'app/img/LOGO_USTA_AZUL.png' %}" alt="Logo" class="logoustagrupo" width="200">

<div class="admincreargrupo">
    <a href="{% url 'app:cerrarsesion' %}">
        <input class="cerrargrupo" type="submit" value="Cerrar Sesión">
    </a>
    <form action="{% url 'app:editarestudianteForm' estudianteenviado.usuario_id %}" method="POST">
        {% csrf_token %}

        <label for="asignaturain" id="lblasignatura">Código* </label>
        <input type="text" id="asignaturain" name="codigo" value="{{estudianteenviado.codigo}}" class="inasignatura">
        <br>
        <br>
        <label for="semestrein" id="lblsemestre">Apellidos* </label>
        <input type="text" id="semestrein" name="apellidos" value="{{estudianteenviado.usuario.last_name}}" class="insemestre">
        <br>
        <br>
        <label for="profesorin" id="lblprofesor">Nombres* </label>
        <input type="text" id="profesorin" name="nombre" value="{{estudianteenviado.usuario.first_name}}" class="inprofesor">
        <br>
        <br>

        <label for="cantidadin" id="lblcantidad">Email* </label>
        <input type="text" id="cantidadin" name="correo" value="{{estudianteenviado.usuario.email}}" class="incantidad">
        <input class="enviarGrupo" type="submit" value="Guardar">

    </form>
</div>
<br>

</form>
{%endblock%}

app/templates/app/editaractividad.html
{% extends "app/base.html" %} {% load static %} {%block css%}
<link rel="stylesheet" href="{% static 'app/css/estilo.css' %}"> {%endblock%} {%block titulo%} Editar Actividad {%endblock%} {%block body%}
<h1>Editar actividad</h1>
<hr>
<a href="{% url 'app:cerrarsesion' %}">
    <input class="cerrarsesion" type="submit" value="Cerrar Sesión">
</a>
<img src="{% static 'app/img/profilephoto.png' %}" alt="profilephoto" width="180">
<br>
<form action="{% url 'app:editaractividadForm' actividadactual.id %}" method="POST">
    {% csrf_token %}
    <p style="color: white;">
        Descripción*
    </p>
    <div>
        <input name="descripcion" value="{{actividadactual.descripcion}}" type=" text " style="WIDTH: 240px; HEIGHT: 100px ">
    </div>
    <div style="position: absolute;left: 280px; ">

        <button onclick="goback() " type="submit ">Editar Actividad</button>

    </div>
</form>
<br> {%endblock%}

app/templates/app/error.html
{% extends "app/base.html" %} {% load static %} {%block css%}
<link rel="stylesheet" href="{% static 'app/css/estilo.css' %}"> {%endblock%} {%block titulo%} Admin {%endblock%} {%block body%}

<h1>ERROR</h1>
{% if errorcreacionestudiante %}
<h3 style="color: wheat;">{{errorcreacionestudiante}}</h3>

{% endif %} {% if errorlogin %}
<h3 style="color: wheat;">{{errorlogin}}</h3>

{% endif %} {% if erroreditargrupo %}
<h3 style="color: wheat;">{{erroreditargrupo}}</h3>

{% endif %} {% if repetircorreo %}
<h3 style="color: wheat;">{{repetircorreo}}</h3>

{% endif %} {% if errorrepetirestudiante %}
<h3 style="color: wheat;">{{errorrepetirestudiante}}</h3>

{% endif %}
<button onclick="goBack()">RETROCEDER</button>

<script>
    function goBack() {
        window.history.back();
    }
</script>

{%endblock%}

app/templates/app/index.html
{% extends "app/base.html" %} {% load static %} {%block css%}
<link rel="stylesheet" href="{% static 'app/css/estilo.css' %}"> {%endblock%} {%block titulo%} Proyecto cloud {%endblock%} {%block body%}
<h1>BIENVENIDO A GRADER</h1>
<div class="autenticacion">
    <form action="{% url 'app:iniciar_sesion'  %}" method="POST">
        {% csrf_token %}
        <h2>USUARIO:</h2>
        <input type="text" name="USUARIO">
        <br>

        <h2>CLAVE:</h2>
        <input type="password" name="password">
        <br>
        <br><br>
        <button type="submit">Iniciar Sesión</button>
    </form>


</div>
<br>
<!-- <a href="{% url 'app:admin' %}">asdiqiwfuqbwf</a> -->
<img class="usta" src=" {% static 'app/img/LOGO_USTA_AZUL.png' %}  " alt="Logo usta">
<br> {%endblock%}

app/templates/app/profesor.html
{% extends "app/base.html" %} {% load static %} {%block css%}
<link rel="stylesheet" href="{% static 'app/css/estilo.css' %}"> {%endblock%} {%block titulo%} Bienvenido profesor {{varprofesores.usuario.last_name}} {%endblock%} {%block body%}
<h1>Bienvenido Profesor {{varprofesores.usuario.last_name}}</h1>
<hr>
<p class="InformacionUsuario">
    {{varprofesores.usuario.first_name}}
    <br> id:{{varprofesores.usuario.id}}
    <br>Correo: {{varprofesores.usuario.email}}

</p>
<a href="{% url 'app:cerrarsesion' %}">
    <input class="cerrarsesion" type="submit" value="Cerrar Sesión">
</a>
<img src="{% static 'app/img/profilephoto.png' %}" alt="profilephoto" width="180">
<br>
<br>
<a href="{% url 'app:crearAcividadProfesor' varprofesores.usuario.id  %}" target="_blank"><input class="Boton" type="submit" value="Crear actividad"></a>
</a>
<br>

<br>
<table class="tablaprofe" border="1">
    <tr>
        <th>Id grupo</th>
        <th>Código</th>
        <th>Asignatura</th>
        <th>Ver</th>
    </tr>
    {%for ver in grupos %}
    <tr>
        <td>{{ver.semestre}}</td>
        <td>{{ver.codigo}}</td>
        <td>{{ver.asignatura}}</td>
        <td>
            <a href="{% url 'app:verGrupoProfesor' ver.id %}" target="_blank">
                <i class="fa fa-eye" aria-hidden="true"></i></a>
        </td>
    </tr>
    {% endfor %}


</table>
<img class="ustaprofe" src="{% static 'app/img/LOGO_USTA_AZUL.png' %}" alt="Logo usta"> {%endblock%}

app/templates/app/verGrupoEstudiante.html
{% extends "app/base.html" %} {% load static %} {%block css%}
<link rel="stylesheet" href="{% static 'app/css/estilo.css' %}">
<link rel="stylesheet" href="{% static 'app/css/estiloGrupoEstudiante.css' %}"> {%endblock%} {%block titulo%} Notas grupo {%endblock%} {%block body%}
<div id="titulo">
    <h1>Notas de un grupo </h1>
    <hr>
</div>
<div class="Datos">
    <div class="FotoPerfil">
        <img src="{% static 'app/img/profilephoto.png' %}" alt="profilephoto" width="180">

    </div>
    <div class="nombres">

        Semestre: {{estudiantegrupo.grupo.semestre}}<br> Asignatura: {{estudiantegrupo.grupo.asignatura}} <br> Profesor: {{estudiantegrupo.grupo.profesor}}
    </div>
    <div class="cerrarsesion1">
        <a href="{% url 'app:cerrarsesion' %}">
            <input class="cerrarsesion" type="submit" value="Cerrar Sesión">
        </a>
    </div>
</div>
<h2 style="color: wheat;">
</h2>
<class class="tabla">
    <table id="tablagrupos" border="1">
        <tr>
            <th>Descripción Actividad</th>
            <th>Nota</th>
        </tr>
        {%for ver in estudiantegrupo.notasestudiante.all %}
        <tr>
            <td>{{ver.actividad.descripcion}}</td>
            <td>{{ver.valor}}</td>
            <!-- {%for ver2 in ver.notasactividad.all%}
            <td>{{ver2.valor}}</td>
            {%endfor%} -->
        </tr>
        {%endfor%}

    </table>



    </div>
    {%endblock%}

app/templates/app/verGrupoProfesor.html
{% extends "app/base.html" %} {% load static %} {%block css%}
<link rel="stylesheet" href="{% static 'app/css/estilo.css' %}"> {%endblock%} {%block titulo%} Ver grupo determinado Profesor {%endblock%} {%block body%}
<h1>Grupo {{grupollegada.asignatura}}</h1>
<hr>
<p class="InformacionUsuario">
    Profesor: {{grupollegada.profesor}}
    <br> Código Grupo: {{grupollegada.codigo}}
    <br> Asignatura: {{grupollegada.asignatura}}
    <!-- <br>{{grupollegada.estudiantesgrupo.all}} -->

</p>
<div>
    <a href="{% url 'app:cerrarsesion' %}">
        <input class="cerrarsesion" type="submit" value="Cerrar Sesión">
    </a>
</div>
<img src="{% static 'app/img/profilephoto.png' %}" alt="profilephoto" width="180">
<br>

</a>
<br>
<br>

<table class="tablaprofe" border="1" style="position: absolute;left: 500px;top: 290px;">
    <tr>
        <th>Apellidos</th>
        <th>Nombres</th>
        <th>Email</th>
        <th>Ver</th>
    </tr>
    {% for ver in grupollegada.estudiantesgrupo.all %}
    <tr>
        <td>{{ver.estudiante.usuario.last_name}}</td>
        <td>{{ver.estudiante.usuario.first_name}}</td>
        <td>{{ver.estudiante.usuario.email}}</td>
        <td>
            <a href="{% url 'app:verEstudianteComoProfesor' ver.estudiante.usuario.id  grupollegada.id  %}">
                <i class="fa fa-eye" aria-hidden="true"></i>
            </a>
        </td>

    </tr>
    {% endfor %}
</table>
<table id="tablaprofe2" border="1">
    <tr>
        <th>Descripción</th>
        <th>Editar</th>
        <th>Ver</th>

    </tr>

    {% for ver1 in grupollegada.actividades.all %}
    <tr>
        <td>{{ver1.descripcion}}</td>
        <td>
            <a href="{% url 'app:editaractividad' ver1.id %}">
                <i class="fa fa-pencil"></i>
            </a>
        </td>
        <td>
            <a href="{% url 'app:verActividadProfesor' ver1.id grupollegada.id %}">
                <i class="fa fa-eye" aria-hidden="true"></i>
            </a>
        </td>

    </tr>
    {% endfor %}
</table>
{%endblock%}

app/templates/app/verGruposComoAdmin.html
{% extends "app/base.html" %} {% load static %} {%block css%}
<link rel="stylesheet" href="{% static 'app/css/estilo.css' %}"> {%endblock%} {%block titulo%} Lista Grupos Admin {%endblock%} {%block body%}

<head>
    <script src="https://use.fontawesome.com/8db3925a16.js"></script>
</head>

<h1>Visualizar grupos en lista</h1>
<hr>
<p class="InformacionUsuario">
    Nombre Admin
    <br> id:Admin
    <br> admin@gmail.com

</p>
<a href="{% url 'app:cerrarsesion' %}">
    <input class="cerrarsesion" type="submit" value="Cerrar Sesión">
</a>
<img src="{% static 'app/img/profilephoto.png' %}" alt="profilephoto" width="180">

<table border="1" style="position: absolute; color: white;">
    <tr class="cabeza">
        <th>Id grupo</th>
        <th>Código</th>
        <th>Asignatura</th>
        <th>Profesor</th>
        <th>Cantidad estudiantes</th>
        <th>Editar grupo</th>
        <th>Ver grupo</th>
        <th>Eliminar grupo</th>

    </tr>
    <tr>

        {%for ver in grupos %}
        <tr>
            <td>{{ver.id}}</td>
            <td>{{ver.codigo}}</td>
            <td>{{ver.asignatura}}</td>
            <td>{{ver.profesor}}</td>
            <td>{{ver.estudiantesgrupo.all |length}}</td>
            <td>
                <a href="{% url 'app:editarGrupoAdmin' ver.id %}"><img src="{% static 'app/img/editar.jpg' %}" alt="editar" width="30"></a>
            </td>
            <td>
                <a href="{% url 'app:verGrupoindividualAdmin' ver.id %}"><i class="fa fa-eye" aria-hidden="true"></i></a>
            </td>
            <td>
                <a href="" onclick="eliminar({{ver.id}})">
                    <i class="fa fa-trash"></i></a>
                <script>
                    function eliminar(idpag) {
                        if (window.confirm("¿Seguro que desea eliminar el grupo " + idpag + " ?")) {

                            window.open("eliminargrupo/" +
                                idpag)
                        }

                    }
                </script>
            </td>
        </tr>
        {% endfor %}


</table>

{%endblock%}

app/templates/app/verListaEstudiantes.html
{% extends "app/base.html" %} {% load static %} {%block css%}
<link rel="stylesheet" href="{% static 'app/css/estiloCrearProfesor.css' %}"> {%endblock%} {%block titulo%} Ver Estudiantes {%endblock%} {%block body%}
<div class="contenedor">
    <div class="title">
        <h1>Ver Estudiantes</h1>
        <hr>
    </div>

    <div class="Datos">
        <div class="FotoPerfil">
            <img src="{% static 'app/img/profilephoto.png' %}" alt="profilephoto" width="180">
        </div>
        <div class="nombres">
            Admin <br> id:Admin <br> Admin@gmail.com
        </div>
        <div class="cerrarsesion1">
            <a href="{% url 'app:cerrarsesion' %}">
                <input class="cerrarsesion" type="submit" value="Cerrar Sesión">
            </a>
        </div>
    </div>

    <div class="creacion">
        <div class="tabla">
            <table id="tablagrupos" border="1">
                <tr class="cabezaestudiantes">
                    <th>Apellidos</th>
                    <th>Nombres</th>
                    <th>E-mail</th>
                    <th>Código</th>
                    <th>Id</th>
                    <th>Editar</th>

                </tr>

                {%for ver in estudiantes %}
                <tr>
                    <td>{{ver.usuario.last_name}}</td>
                    <td>{{ver.usuario.first_name}}</td>
                    <td>{{ver.usuario.email}}</td>
                    <td>{{ver.codigo}}</td>
                    <td>{{ver.usuario.id}}</td>
                    <td>
                        <a href="{% url 'app:editarEstudiante' ver.usuario_id %}"><i class="fa fa-eye" aria-hidden="true"></i></a>
                    </td>
                </tr>
                {% endfor %}


            </table>
        </div>
    </div>
    <a href="{% url 'app:admin' %}">
        <input class="Boton" type="submit" value="Regresar">
    </a>
</div>
{%endblock%}